In [1]:
from FFN_model import *

In [2]:
model = FFN([5, 8, 4, 8, 5])

In [3]:
model.dimensions

{'neuron_activation_vector': [5, 8, 4, 8, 5],
 'weight_matrix': [[8, 5], [4, 8], [8, 4], [5, 8]],
 'bias_vector': [8, 4, 8, 5]}

In [4]:
model.trainable_parameters[0]["B"]

array([0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
model.trainable_parameters[1]["W"]

array([[-0.57132108,  0.99933494, -0.28958272,  0.75524312, -0.10980853,
        -0.48520859, -0.92225794, -0.30556058],
       [ 0.14070982,  0.54507208, -0.97104385, -0.62577169,  0.23531806,
         0.97678101,  0.21103706, -0.0157858 ],
       [-0.92832331, -0.76354254, -0.36924772, -0.08864022,  0.13706938,
         0.8277101 , -0.92303178,  0.94481034],
       [ 0.49833719, -0.25475806,  0.77054151, -0.84280023,  0.20484787,
         0.57486096,  0.89496326, -0.12126972]])

In [6]:
encoder, decoder = scalar_vector_encoding_factory(
    min = 0,
    max = 10,
    neurons = 5
)

In [7]:
print(encoder(3.0))
print(decoder(encoder(3.0)))

[1.0, 0.5, 0.0, 0.0, 0.0]
3.0


In [8]:
encoder, decoder = scalar_vector_encoding_factory(
    min = -50,
    max = 50,
    neurons = 10
)

In [9]:
print(encoder(37.0))
print(decoder(encoder(37.0)))
print(encoder(-19.0))
print(decoder(encoder(-19.0)))

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6999999999999993, 0.0]
36.999999999999986
[1.0, 1.0, 1.0, 0.10000000000000009, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
-19.0


In [10]:
relu = Leaky_Relu()
for _ in range(10):
    num = uniform(-20, 20)
    print(f"relu({[num]})  =  {relu.standard([num])}")
    print(f"relu'({[num]})  =  {relu.derivative([num])}")

relu([-2.297075858806533])  =  [-0.0]
relu'([-2.297075858806533])  =  [0]
relu([18.78072658861945])  =  [18.78072658861945]
relu'([18.78072658861945])  =  [1]
relu([8.512380928754808])  =  [8.512380928754808]
relu'([8.512380928754808])  =  [1]
relu([19.39813843359414])  =  [19.39813843359414]
relu'([19.39813843359414])  =  [1]
relu([15.36762607414979])  =  [15.36762607414979]
relu'([15.36762607414979])  =  [1]
relu([17.245704665033223])  =  [17.245704665033223]
relu'([17.245704665033223])  =  [1]
relu([18.138037574029063])  =  [18.138037574029063]
relu'([18.138037574029063])  =  [1]
relu([-6.2081381469307])  =  [-0.0]
relu'([-6.2081381469307])  =  [0]
relu([10.258395174692438])  =  [10.258395174692438]
relu'([10.258395174692438])  =  [1]
relu([16.61542585228913])  =  [16.61542585228913]
relu'([16.61542585228913])  =  [1]


In [11]:
for _ in range(10):
    length = randint(1, 10)
    vector = [uniform(-20, 20) for _ in range(length)]
    print(f"relu({vector})  =  {relu.standard(vector)}")
    print(f"relu'({vector})  =  {relu.derivative(vector)}")

relu([10.890011659304392, -14.779326449872485, 18.084069179297657])  =  [10.890011659304392, -0.0, 18.084069179297657]
relu'([10.890011659304392, -14.779326449872485, 18.084069179297657])  =  [1, 0, 1]
relu([-8.687454098938122, -16.37332880201461, -10.716057019502113, 2.3100026286184026, -3.8441015647678825, -0.6471607646434983, 8.074511467914899, 13.27136379887024])  =  [-0.0, -0.0, -0.0, 2.3100026286184026, -0.0, -0.0, 8.074511467914899, 13.27136379887024]
relu'([-8.687454098938122, -16.37332880201461, -10.716057019502113, 2.3100026286184026, -3.8441015647678825, -0.6471607646434983, 8.074511467914899, 13.27136379887024])  =  [0, 0, 0, 1, 0, 0, 1, 1]
relu([-19.445422281997295, -16.75916541917357, -6.856471772102806, 8.880090486436075, 0.6383391519836437, 16.439413150361446, -9.071710297441914, 16.16720782633532, 2.9952296655308857])  =  [-0.0, -0.0, -0.0, 8.880090486436075, 0.6383391519836437, 16.439413150361446, -0.0, 16.16720782633532, 2.9952296655308857]
relu'([-19.445422281997295

In [12]:
mse = MSE()
print(mse.standard(numpy.array([1, 2, 3]), numpy.array([2, 2, 2])))
print(mse.derivative(numpy.array([1, 2, 3]), numpy.array([2, 2, 2])))

0.6666666666666666
[-0.66666667  0.          0.66666667]


In [13]:
mse = MSE()
for _ in range(10):
    length = randint(1, 5)
    Y = numpy.array([uniform(-20, 20) for _ in range(length)])
    true_Y = numpy.array([uniform(-20, 20) for _ in range(length)])
    print(f"mse({Y}, {true_Y})  =  {mse.standard(Y, true_Y)}")
    print(f"mse'({Y}, {true_Y})  =  {mse.derivative(Y, true_Y)}")


mse([-3.70482033  2.5393611 ], [10.33271684 -0.37062857])  =  102.76024478356703
mse'([-3.70482033  2.5393611 ], [10.33271684 -0.37062857])  =  [-14.03753717   2.90998967]
mse([13.45112917 -4.16310244 16.69693243], [-3.13416403  3.93293053 -3.63237455])  =  251.29947416422254
mse'([13.45112917 -4.16310244 16.69693243], [-3.13416403  3.93293053 -3.63237455])  =  [11.05686213 -5.39735531 13.55287132]
mse([  0.954275  -11.1432543], [ 13.77685629 -15.53889614])  =  91.87012911392038
mse'([  0.954275  -11.1432543], [ 13.77685629 -15.53889614])  =  [-12.82258129   4.39564184]
mse([-1.20211781 11.53476507 19.20867053  1.3859636 ], [ -3.26235098  16.06947524 -16.13275264 -12.03756522])  =  363.5038686447315
mse'([-1.20211781 11.53476507 19.20867053  1.3859636 ], [ -3.26235098  16.06947524 -16.13275264 -12.03756522])  =  [ 1.03011659 -2.26735508 17.67071159  6.71176441]
mse([ 10.36543448 -14.34098947  12.36509124  11.47875454  -5.62913816], [-1.18169982  9.48161928  8.25681293  6.63466251  0.43

In [14]:
encoder, decoder = scalar_vector_encoding_factory(
    min = -20,
    max = 20,
    neurons = 5
)
model = FFN(
    neurons_per_layer = [5, 20, 10, 5, 10, 20, 5],
    encoder = encoder,
    decoder = lambda x:x,
)

In [15]:
model.predict(5)

array([ 2.71523512, -2.55113741, -2.94073684,  0.04847134,  2.87580295])

In [16]:
encoder, decoder = scalar_vector_encoding_factory(
    min = -100,
    max = 100,
    neurons = 20
)
model = FFN(
    neurons_per_layer = [20, 20, 10, 5, 10, 20, 20],
    encoder = encoder,
    decoder = decoder,
)


In [17]:
for num in range(-10, 10):
    print(f"model.predict({float(num)}) = {model.predict(float(num))}")

model.predict(-10.0) = -100.0
model.predict(-9.0) = -100.0
model.predict(-8.0) = -100.0
model.predict(-7.0) = -100.0
model.predict(-6.0) = -100.0
model.predict(-5.0) = -100.0
model.predict(-4.0) = -100.0
model.predict(-3.0) = -100.0
model.predict(-2.0) = -100.0
model.predict(-1.0) = -100.0
model.predict(0.0) = -100.0
model.predict(1.0) = -100.0
model.predict(2.0) = -100.0
model.predict(3.0) = -100.0
model.predict(4.0) = -100.0
model.predict(5.0) = -100.0
model.predict(6.0) = -100.0
model.predict(7.0) = -100.0
model.predict(8.0) = -100.0
model.predict(9.0) = -100.0
